import type { Metadata } from "next";
import Image from "next/image";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = { title: "Accommodation", description: "Explore places for your community to stay." };
const types=[["Hotels","Comfort, service and convenient locations.","/images/destinations/south-africa-card.webp"],["Apartments","Flexible shared spaces with room to settle in.","/images/destinations/india-card.webp"],["Homestays","Welcoming stays with a stronger sense of place.","/images/destinations/uganda-card.webp"],["Lodges","Nature-led stays for memorable group escapes.","/images/destinations/kenya-card.webp"],["Villas","Private spaces designed for time together.","/images/destinations/seychelles-card.webp"]] as const;

export default function AccommodationPage(){return <div className="min-h-screen bg-ink text-cream"><Header/><main>
  <section className="relative isolate overflow-hidden border-b border-line"><Image src="/images/destinations/seychelles-hero.webp" alt="A relaxing place for a community trip" fill priority sizes="100vw" className="z-0 object-cover"/><div className="absolute inset-0 z-10 bg-gradient-to-r from-ink via-ink/85 to-ink/35"/><div className="relative z-20 mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.22em] text-gold">Accommodation</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold leading-tight sm:text-6xl">Find the right place for your community to stay.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-cream/85">Explore stays that give your group the comfort, flexibility and shared space it needs.</p><a href="#stays" className="mt-8 inline-flex rounded-xl bg-gold px-5 py-3 text-sm font-semibold text-ink">Explore Accommodation</a></div></section>
  <section id="stays" className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">Places to stay</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-5xl">Stay your way.</h2></div><p className="max-w-md text-sm leading-6 text-sand">A design preview of accommodation types. Availability and booking connections will follow after approval.</p></div><div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{types.map(([title,copy,image])=><article key={title} className="group overflow-hidden rounded-2xl border border-line bg-surface"><div className="relative aspect-[4/3] overflow-hidden"><Image src={image} alt="" fill sizes="(min-width:1024px) 20vw, 50vw" className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-3 sm:p-5"><h3 className="font-display text-lg font-semibold sm:text-xl">{title}</h3><p className="mt-2 text-xs leading-5 text-sand sm:text-sm sm:leading-6">{copy}</p><span className="mt-4 block text-xs font-semibold text-gold">Explore stays →</span></div></article>)}</div></section>
  <section className="border-t border-line bg-surface"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="rounded-3xl border border-lineStrong bg-ink p-7 text-center sm:p-10"><h2 className="font-display text-3xl font-semibold">Designed around community trips.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-sand">Compare spaces by group size, destination and stay style when accommodation inventory is connected.</p></div></div></section>
  </main><Footer/></div>}
