import type { Metadata } from "next";
import Image from "next/image";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = { title: "Events", description: "Discover community-friendly events and shared experiences." };
const eventCards=[["Sunset culture market","Culture","Nairobi, Kenya","24 Aug","/images/destinations/kenya-card.webp"],["Community food weekend","Food","Cape Town, South Africa","07 Sep","/images/destinations/south-africa-card.webp"],["Desert music gathering","Music","Marrakech, Morocco","19 Oct","/images/destinations/morocco-card.webp"],["Lakeside wellness day","Wellness","Kigali, Rwanda","02 Nov","/images/destinations/rwanda-card.webp"],["Heritage walk & stories","Heritage","Jaipur, India","16 Nov","/images/destinations/india-card.webp"],["Coastal outdoor festival","Outdoors","Zanzibar, Tanzania","30 Nov","/images/destinations/tanzania-card.webp"]] as const;

export default function EventsPage(){return <div className="min-h-screen bg-ink text-cream"><Header/><main>
  <section className="relative isolate overflow-hidden border-b border-line"><Image src="/images/destinations/morocco-hero.webp" alt="A destination ready for shared community events" fill priority sizes="100vw" className="z-0 object-cover"/><div className="absolute inset-0 z-10 bg-gradient-to-r from-ink via-ink/88 to-ink/35"/><div className="relative z-20 mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.22em] text-gold">Events</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold sm:text-6xl">Enjoy events with your community.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-cream/85">Discover events your community can attend together and create shared experiences.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#upcoming" className="rounded-xl bg-gold px-5 py-3 text-sm font-semibold text-ink">Explore Events</a><button type="button" disabled aria-disabled="true" className="cursor-not-allowed rounded-xl border border-white/25 bg-ink/50 px-5 py-3 text-sm font-semibold text-sand"><span className="block">Create Event</span><span className="block text-[10px] uppercase tracking-wider text-sandDim">Coming soon</span></button></div></div></section>
  <section id="upcoming" className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">Upcoming & featured</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-5xl">Shared moments worth planning for.</h2></div><div className="flex flex-wrap gap-2">{["All","Culture","Food","Music","Wellness","Outdoors"].map((item,index)=><span key={item} className={`rounded-full border px-3 py-2 text-xs ${index===0?"border-gold bg-gold text-ink":"border-lineStrong text-sand"}`}>{item}</span>)}</div></div><div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:gap-5">{eventCards.map(([title,category,location,date,image])=><article key={title} className="group overflow-hidden rounded-2xl border border-line bg-surface"><div className="relative aspect-[4/3] overflow-hidden"><Image src={image} alt="" fill sizes="(min-width:640px) 33vw, 50vw" className="object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-2 top-2 rounded-full bg-ink/85 px-2 py-1 text-[10px] font-semibold text-gold">{category}</span><span className="absolute right-2 top-2 rounded-lg bg-cream px-2 py-1 text-center text-[10px] font-bold text-ink">{date}</span></div><div className="p-3 sm:p-5"><h3 className="font-display text-base font-semibold sm:text-xl">{title}</h3><p className="mt-2 text-[11px] text-sand sm:text-sm">{location}</p><p className="mt-3 hidden text-sm leading-6 text-sand sm:block">A community-friendly event designed to be enjoyed together.</p><span className="mt-4 block text-xs font-semibold text-gold">View event details →</span></div></article>)}</div></section>
  <section className="border-t border-line bg-surface"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="rounded-3xl border border-gold/20 bg-gold/10 p-7 sm:p-10"><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">For community leaders</p><h2 className="mt-3 font-display text-3xl font-semibold">Event creation is coming later.</h2><p className="mt-4 max-w-2xl leading-7 text-sand">The creation flow will be introduced after the event discovery design and experience have been reviewed.</p><button type="button" disabled className="mt-7 cursor-not-allowed rounded-xl border border-lineStrong px-5 py-3 text-sm font-semibold text-sandDim">Create Event · Coming Soon</button></div></div></section>
  </main><Footer/></div>}
