"use client";
import { useMemo, useState } from "react";
import OfferingCard from "./OfferingCard";
import type { Offering } from "@/types/destination";

export default function InventoryExplorer({ offerings, countries }: { offerings: readonly Offering[]; countries: readonly string[] }) {
  const [query,setQuery]=useState(""); const [country,setCountry]=useState(""); const [category,setCategory]=useState(""); const [price,setPrice]=useState(""); const [duration,setDuration]=useState("");
  const results=useMemo(()=>offerings.filter((item)=>{ const haystack=`${item.country} ${item.title} ${item.location} ${item.category}`.toLowerCase(); const q=query.trim().toLowerCase(); const normalized=item.currency==="KES"?item.price/130:item.price; const priceOk=!price||(price==="low"?normalized<100:price==="mid"?normalized>=100&&normalized<=500:normalized>500); const durationOk=!duration||(duration==="short"?item.category==="activity":duration==="day"?item.category==="day-trip":item.category==="package"); return (!q||haystack.includes(q))&&(!country||item.country===country)&&(!category||item.category===category)&&priceOk&&durationOk;}),[offerings,query,country,category,price,duration]);
  const reset=()=>{setQuery("");setCountry("");setCategory("");setPrice("");setDuration("");};
  const selectClass="rounded-xl border border-lineStrong bg-surface px-3 py-3 text-sm text-cream outline-none focus:border-gold focus:ring-2 focus:ring-gold/20";
  return <section aria-labelledby="inventory-heading" className="mt-20 border-t border-line pt-14"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">Development catalogue</p><h2 id="inventory-heading" className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Search preview experiences</h2><p className="mt-3 text-sand">Preview data — live availability and pricing will be connected later.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="lg:col-span-2"><span className="sr-only">Search inventory</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search safari, Nairobi, beach…" className={`${selectClass} w-full`} /></label><select aria-label="Filter by country" value={country} onChange={e=>setCountry(e.target.value)} className={selectClass}><option value="">All countries</option>{countries.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)} className={selectClass}><option value="">All categories</option><option value="activity">Activities</option><option value="day-trip">Day trips</option><option value="package">Packages</option></select><select aria-label="Filter by price" value={price} onChange={e=>setPrice(e.target.value)} className={selectClass}><option value="">Any price</option><option value="low">Budget</option><option value="mid">Mid-range</option><option value="high">Premium</option></select><select aria-label="Filter by duration" value={duration} onChange={e=>setDuration(e.target.value)} className={selectClass}><option value="">Any duration</option><option value="short">Hours</option><option value="day">Full day</option><option value="multi">Multiple days</option></select></div><p className="my-6 font-mono text-xs uppercase tracking-widest text-sandDim" aria-live="polite">{results.length} demo experiences</p>{results.length?<div className="grid gap-5 lg:grid-cols-3">{results.map(item=><OfferingCard key={item.id} offering={item}/>)}</div>:<div className="rounded-2xl border border-dashed border-lineStrong bg-surface p-10 text-center"><p className="text-sand">No experiences match your current filters.</p><button onClick={reset} className="mt-4 rounded-lg bg-gold px-4 py-2 text-sm font-semibold text-ink">Reset filters</button></div>}</section>;
}
