import type { Metadata } from "next";
import Image from "next/image";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = { title: "Groups", description: "Discover open communities and closed groups built around shared interests." };

const interests = ["Adventure", "Culture", "Food", "Nature", "Wellness", "Family travel"];

export default function GroupsPage() {
  return <div className="min-h-screen bg-ink text-cream"><Header/><main>
    <section className="relative isolate overflow-hidden border-b border-line"><Image src="/images/destinations/rwanda-hero.webp" alt="People connecting through shared travel interests" fill priority sizes="100vw" className="z-0 object-cover"/><div className="absolute inset-0 z-10 bg-gradient-to-r from-ink via-ink/90 to-ink/45"/><div className="relative z-20 mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.22em] text-gold">Groups</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold leading-tight sm:text-6xl">Find your people. Shape the journey together.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-cream/85">Join common-interest groups, connect with others, and form a community — or create your own community.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#discover" className="rounded-xl bg-gold px-5 py-3 text-sm font-semibold text-ink">Explore Communities</a><a href="#closed" className="rounded-xl border border-white/25 bg-ink/50 px-5 py-3 text-sm font-semibold">Join a Group</a><button type="button" className="rounded-xl border border-white/25 bg-cream/10 px-5 py-3 text-sm font-semibold">Create a Community</button></div></div></section>
    <section id="discover" className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">Community discovery</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-5xl">Choose how you want to connect.</h2></div><div className="mt-9 grid gap-5 lg:grid-cols-2"><GroupType badge="Open community" title="Discover common-interest communities" copy="Open spaces where travellers can browse, connect and join conversations around shared interests." tone="gold"/><div id="closed"><GroupType badge="Closed group" title="Plan privately with people you know" copy="Invitation-based spaces for friends, families, teams and organisations planning together." tone="neutral"/></div></div></section>
    <section className="border-y border-line bg-surface"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">Common interests</p><h2 className="mt-3 font-display text-3xl font-semibold">Start with what brings you together.</h2><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{interests.map((interest)=><article key={interest} className="rounded-2xl border border-lineStrong bg-ink p-5 text-center"><div className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-gold/15 text-gold">✦</div><h3 className="mt-4 text-sm font-semibold">{interest}</h3></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div className="rounded-3xl border border-gold/25 bg-gradient-to-r from-gold/15 to-surface p-7 sm:p-10"><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">Community creation</p><h2 className="mt-3 max-w-2xl font-display text-3xl font-semibold sm:text-4xl">Create a space for your community.</h2><p className="mt-4 max-w-2xl leading-7 text-sand">Bring people together around a shared purpose, interest or upcoming journey.</p><button type="button" className="mt-7 rounded-xl bg-gold px-5 py-3 text-sm font-semibold text-ink">Create a Community</button></div></section>
  </main><Footer/></div>;
}

function GroupType({badge,title,copy,tone}:{badge:string;title:string;copy:string;tone:"gold"|"neutral"}){return <article className={`h-full rounded-3xl border p-6 sm:p-8 ${tone==="gold"?"border-gold/30 bg-gold/10":"border-lineStrong bg-surface"}`}><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${tone==="gold"?"border-gold/30 text-gold":"border-lineStrong text-sand"}`}>{badge}</span><h3 className="mt-8 font-display text-3xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-sand">{copy}</p><button type="button" className={`mt-7 rounded-xl px-5 py-3 text-sm font-semibold ${tone==="gold"?"bg-gold text-ink":"border border-lineStrong text-cream"}`}>{tone==="gold"?"Explore Communities":"Join a Group"}</button></article>}
